var autogenRegexps = [
    /\d{4,}/,
    /^ember\d+/,
    /^[0-9_-]+$/,
    /^_\d{2,}/,
    /([a-f_-]*[0-9_-]){6,}/i
];

/**
 * check auto-generated selectors
 * @param {String} val
 * @return {boolean} is auto-generated
 */
function autogenCheck(val){
    if(!val){
        return false;
    }
    var autogenerated = _.find(autogenRegexps,function(reg){
        return reg.test(val);
    });
    return !!autogenerated;

}
exports.autogenCheck = autogenCheck;
